/** The ruler's small, ordinary day. These activities do not change a board. */
export const JOURNEY = {
  you: 'You, out in the town',
  changeWork: 'Spend a little time',
  jobs: {
    lanes: 'Walking the lanes',
    fields: 'Tending the field',
    wood: 'Helping with the timber',
  },
  heading: 'A word on the road',
  more: 'The rest of it',
  approaching: 'Someone is coming to find you',
  waiting: 'A visitor is waiting while you finish',
  speaking: 'There is something you should see.',
  animalCaller: 'A neighbour',
  go: 'Show me the way',
  walking: 'On the way',
  arriving: 'You will decide when you get there.',
  arrived: 'Here, where it happened',
  fetching: 'Going to lend a hand',
  doing: 'A minute of your day',
  queue: '{n} small things to do',
  queueOne: 'One small thing to do',
  reserved: 'You are on your way. This will wait for you.',
  queued: 'Next on your walk',
  devSkip: 'Skip this walk',
  devInstant: 'Instant journeys',
  devWeather: 'Next season',
  tasks: {
    pet: 'Stopping to scratch the dog',
    lift: 'Gathering the apples',
    pull: 'Helping land the catch',
    catch: 'Bringing the kid back',
  },
};
